name: "Build 🔨"

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches: [ main ]

jobs:
  build:
    name: "Build 🔨"
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        scheme:
          - "Swiftfin"
          - "Swiftfin tvOS"

    runs-on: macos-26

    env:
      XCODE_VERSION: "26.6"

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0'
          bundler-cache: true

      - name: Install Homebrew dependencies
        run: brew bundle --file Brewfile

      # FIXME: caches would keep failed compiles?

      # - name: Cache Swift packages
      #   uses: actions/cache@v4
      #   with:
      #     path: PackageCache
      #     key: ${{ runner.os }}-${{ matrix.scheme }}-spm-${{ hashFiles('**/Package.resolved') }}
      #     restore-keys: ${{ runner.os }}-${{ matrix.scheme }}-spm-

      - name: Build
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 60
          command: bundle exec fastlane buildLane \
            scheme:"\"${{ matrix.scheme }}\"" \
            xcodeVersion:${{ env.XCODE_VERSION }}
